# MySQL Dockerfile
FROM mysql:8.0

# Configurar el conjunto de caracteres por defecto
ENV MYSQL_CHARSET=utf8mb4
ENV MYSQL_COLLATION=utf8mb4_unicode_ci

# Exponer el puerto por defecto de MySQL
EXPOSE 3306